import { useState } from 'react';
import { categories,type Category } from '../shared/model';
import { canView,money,stage,totals } from '../shared/domain';
import { useStore } from './store';
import { Empty,Header,Progress,go } from './ui';
const initial=()=>{try{return JSON.parse(sessionStorage.getItem('gantsta.filters')||'{}')}catch{return {}}};
export function Dashboard(){const {bundle,profile}=useStore();const [filters,setFilters]=useState<{category:Category;search:string;period:string;status:string}>(()=>({category:'Cursos',search:'',period:'all',status:'all',...initial()}));if(!profile)return null;const available=bundle.offerings.filter(o=>canView(profile,o));const periods=[...new Set(available.map(o=>o.start.slice(0,7)))].sort().reverse();function update(part:Partial<typeof filters>){const next={...filters,...part};setFilters(next);sessionStorage.setItem('gantsta.filters',JSON.stringify(next));}const matches=available.filter(o=>{const s=stage(totals(bundle.entries[o.id]||[],o.start,o.end).closed,o.goal);return o.category===filters.category&&o.name.toLocaleLowerCase().includes(filters.search.toLocaleLowerCase())&&(filters.period==='all'||o.start.slice(0,7)<=filters.period&&o.end.slice(0,7)>=filters.period)&&(filters.status==='all'||filters.status==='done'&&s.percentage>=100||filters.status==='progress'&&s.percentage>0&&s.percentage<100||filters.status==='zero'&&s.percentage===0)});
return <><div className="topline"><span className="wordmark">gantsta<span>®</span></span><button className="avatar" aria-label="Abrir mi cuenta" onClick={()=>go('/account')}>{profile.name.slice(0,2).toUpperCase()}</button></div><Header title="Dashboard" description="Tus offerings, de un vistazo."/><div className="category-tabs" role="tablist" aria-label="Categorías">{categories.map(c=><button key={c} role="tab" id={'tab-'+c} aria-selected={filters.category===c} aria-controls="offerings-list" onClick={()=>update({category:c,search:''})}>{c}</button>)}</div><label className="searchbox"><span aria-hidden="true">⌕</span><input aria-label="Buscar clase o producto" type="search" placeholder="Buscar clase o producto…" value={filters.search} onChange={e=>update({search:e.target.value})}/></label><div className="columns"><select aria-label="Filtrar por avance" value={filters.status} onChange={e=>update({status:e.target.value})}><option value="all">Todos los avances</option><option value="progress">En progreso</option><option value="done">Objetivo conseguido</option><option value="zero">Sin avance</option></select><select aria-label="Filtrar por periodo" value={filters.period} onChange={e=>update({period:e.target.value})}><option value="all">Todos los periodos</option>{periods.map(p=><option key={p} value={p}>{new Date(p+'-15T12:00:00').toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</option>)}</select></div><div className="list-heading"><span>OFFERINGS</span><span>{matches.length} productos</span></div><div role="tabpanel" id="offerings-list" aria-labelledby={'tab-'+filters.category}>{matches.map(o=>{const result=totals(bundle.entries[o.id]||[],o.start,o.end),s=stage(result.closed,o.goal);return <button key={o.id} className="offering-card" onClick={()=>go('/offering/'+o.id)}><div className="row"><div><h2>{o.name}</h2><p className="muted">{money(o.price)} · {o.billing.toLowerCase()}</p></div><span className="arrow" aria-hidden="true">›</span></div><div className="sales-row"><span className="sales-count">{result.closed}<small> / {o.goal} {o.unit.toLowerCase()}</small></span><strong className={'percentage '+s.color}>{s.percentage} %</strong></div><Progress value={s.percentage} color={s.color} label={'Avance de '+o.name}/><div className="row"><span className={'state '+s.color}>{s.label}</span><span className="muted small">{result.closed>=o.goal?'Meta alcanzada':'Faltan '+(o.goal-result.closed)}</span></div></button>})}{!matches.length?<Empty>No hay offerings con estos filtros.{profile.role==='admin'?<button className="text-button" onClick={()=>go('/new')}>Crear offering →</button>:null}</Empty>:null}</div></>;
}
