import { useState,type FormEvent } from 'react';
import { categories,milestones,platforms,type Offering } from '../shared/model';
import { addDays,dayCount,money,totalBudget,validateOffering,weeklyTargets } from '../shared/domain';
import { newOffering } from './data';
import { useStore } from './store';
import { Back,ErrorText,Field,Header,go } from './ui';
export function OfferingForm({existing}:{existing?:Offering}){const {profile,bundle,saveOffering}=useStore();const [o,setO]=useState(()=>existing?structuredClone(existing):newOffering(profile!.id)),[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);const people=bundle.profiles.filter(p=>p.status==='active');function patch(values:Partial<Offering>){setO(prev=>({...prev,...values}))}function schedule(start:string,end:string,goal:number){const days=dayCount(start,end);patch({start,end,goal,targets:weeklyTargets(start,end,goal),milestoneDates:Number.isFinite(days)&&days>0?[start,addDays(start,Math.round((days-1)*.2)),addDays(start,Math.round((days-1)*.45)),end]:o.milestoneDates})}async function submit(e:FormEvent){e.preventDefault();setError('');const next={...o,name:o.name.trim(),memberIds:[...new Set([o.ownerId,...o.memberIds])],driveUrl:o.driveUrl.trim()};try{validateOffering(next);if(step<2){setStep(step+1);window.scrollTo(0,0);return;}setBusy(true);await saveOffering(next);go('/offering/'+o.id);}catch(cause){setError((cause as Error).message);}finally{setBusy(false)}}
return <><Back to={existing?'/offering/'+existing.id:'/admin'} label={existing?'Offering':'Administración'}/><Header eyebrow="ADMINISTRACIÓN" title={existing?'Editar offering':'Crear offering'} description="Un producto. Un objetivo. Un plan."/><div className="steps">{['Producto','Objetivo','Equipo'].map((s,i)=><div key={s} className={i<=step?'active':''} aria-current={step===i?'step':undefined}>{i+1}. {s}</div>)}</div><form onSubmit={submit}>
{step===0?<><Field label="Nombre del producto"><input required maxLength={100} value={o.name} placeholder="Clases regulares" onChange={e=>patch({name:e.target.value})}/></Field><Field label="Categoría"><select value={o.category} onChange={e=>patch({category:e.target.value as Offering['category']})}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><div className="columns"><Field label="Precio (€)"><input type="number" min="0" step="0.01" required inputMode="decimal" value={o.price/100} onChange={e=>patch({price:Math.round(Number(e.target.value)*100)})}/></Field><Field label="Tipo de cobro"><select value={o.billing} onChange={e=>patch({billing:e.target.value as Offering['billing']})}><option>Por inscripción</option><option>Mensual</option><option>Por unidad</option></select></Field></div><Field label="Descripción · opcional"><textarea value={o.description} maxLength={2000} rows={3} onChange={e=>patch({description:e.target.value})}/></Field></>:null}
{step===1?<><div className="columns"><Field label="Fecha de inicio"><input type="date" required value={o.start} onChange={e=>schedule(e.target.value,o.end,o.goal)}/></Field><Field label="Fecha de fin"><input type="date" min={o.start} required value={o.end} onChange={e=>schedule(o.start,e.target.value,o.goal)}/></Field></div><Field label="Tipo de objetivo"><select value={o.unit} onChange={e=>patch({unit:e.target.value})}><option>Inscripciones</option><option>Reservas</option><option>Unidades vendidas</option></select></Field><Field label="Cantidad objetivo"><input type="number" required min="1" step="1" inputMode="numeric" value={o.goal} onChange={e=>schedule(o.start,o.end,Number(e.target.value))}/></Field><details className="surface budget-editor" open><summary><strong>Presupuesto por plataforma</strong><span>Total: {money(totalBudget(o))}</span></summary><p className="small muted">Asigna el presupuesto para todo el periodo.</p>{platforms.map(p=><div key={p} className="platform-editor"><label className="check"><input type="checkbox" checked={o.enabledPlatforms.includes(p)} onChange={e=>patch({enabledPlatforms:e.target.checked?[...o.enabledPlatforms,p]:o.enabledPlatforms.filter(v=>v!==p)})}/>{p} Ads</label>{o.enabledPlatforms.includes(p)?<Field label={'Importe para '+p+' (€)'}><input type="number" min="0" step="0.01" required inputMode="decimal" value={o.budgets[p]/100} onChange={e=>patch({budgets:{...o.budgets,[p]:Math.round(Number(e.target.value)*100)}})}/></Field>:null}</div>)}</details><section className="surface"><h2>Metas de ventas</h2><p className="small muted">Cantidades acumuladas hasta cada fecha. Se recalculan al cambiar el periodo o el objetivo.</p>{o.targets.map((t,i)=><label key={t.date} className="target-row"><span>Hasta {t.date.split('-').reverse().join('/')}</span><input aria-label={'Meta hasta '+t.date} type="number" required min={i?o.targets[i-1].count:0} max={o.goal} step="1" value={t.count} onChange={e=>patch({targets:o.targets.map((v,j)=>j===i?{...v,count:Number(e.target.value)}:v)})}/></label>)}</section></>:null}
{step===2?<><Field label="Responsable del offering"><select value={o.ownerId} required onChange={e=>patch({ownerId:e.target.value,memberIds:[...new Set([...o.memberIds,e.target.value])]})}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><section className="surface"><h2>Colaboradores</h2>{people.filter(p=>p.id!==o.ownerId).map(p=><label className="check" key={p.id}><input type="checkbox" checked={o.memberIds.includes(p.id)} onChange={e=>patch({memberIds:e.target.checked?[...o.memberIds,p.id]:o.memberIds.filter(v=>v!==p.id)})}/>{p.name}</label>)}</section><section className="surface"><h2>Fechas de los hitos</h2>{milestones.map((m,i)=><label className="target-row" key={m}><span>{m}</span><input type="date" required min={i?o.milestoneDates[i-1]:o.start} max={o.end} value={o.milestoneDates[i]} onChange={e=>patch({milestoneDates:o.milestoneDates.map((v,j)=>i===j?e.target.value:v)})}/></label>)}</section><Field label="Carpeta de Drive · opcional"><input type="url" value={o.driveUrl} placeholder="https://drive.google.com/drive/folders/…" onChange={e=>patch({driveUrl:e.target.value})}/></Field><p className="small muted">Después podrás añadir tareas desde Planificación.</p></>:null}
<ErrorText error={error}/><button className="primary" disabled={busy}>{busy?'Guardando…':step<2?'Continuar →':existing?'Guardar cambios':'Crear offering'}</button>{step>0?<button className="text-button" type="button" disabled={busy} onClick={()=>{setStep(step-1);setError('')}}>← Volver al paso anterior</button>:null}</form></>;
}
